baseurl: "/"
languageCode: "en-us"
title: "Angold's Blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

output:
  blogdown::html_page:
    toc: true

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Angold WANG's Blog."
  footer: "&copy; [Angold WANG](https://angold.blog) 2023 -- {Year} | [Github](https://github.com/Angold-4) | [Twitter](https://twitter.com/wAngold4w)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      table: true
